### ISSUE TITLE
Not compatible with macOS Catalina

### ISSUE THREAD

**Issue by jchrismills** [ooni/probe-desktop#35]
Won't run at all in MacOS Catalina Version 10.15 Beta 19A501i
Will be installing the latest dev beta shortly and will update.

Issue is:
"OONI Probe.app" can't be opened because Apple cannot check it for malicious software. 
This software needs to be updated. Contact the developer for more information.

Also tried opening from System Preferences>Security & Privacy by unlocking the make changes and click the "Open Anyway" button....Same message as above continues to appear. 
![by default 2019-07-25 at 11 41 34 am](https://user-images.githubusercontent.com/31445196/61888353-5b9e2700-aed1-11e9-8bb2-2127e9e12fd9.png)

**Comment by sarathms** [comment]
This should be fixed in the recent code-signed release candidate versions. @hellais can you confirm?

**Comment by hellais** [comment]
Yes that is true. Have since rc.2 started signing the applications using our Apple developer ID key and have enabled gatekeeper with notarization which should allow it work without issues in macOS Catalina.

I haven't upgrade to it yet so I can't test it, but it would be great if you let us know if the latest build works for you: https://github.com/ooni/probe-desktop/releases/tag/v3.0.0-rc.3

**Comment by hellais** [comment]
I am closing this issue as fixed. @jchrismills please do report back if you have any issues (or even if it works!), thanks!
