### ISSUE TITLE
Incomplete tests crash Test Results screen

### ISSUE THREAD

**Issue by sarathms** [ooni/probe-desktop#48]
When there are results with `{is_done: false}`, the Test Results listing screen crashes because the incomplete tests appear on top of the older test in the `results` array and breaks the chronology of the tests.

**Comment by sarathms** [comment]
@hellais A broader question is how do we want to show incomplete tests in the 'Test Results' screen. On mobile, we show it along with the other results with `N/A` in the preview. 
On CLI, `ooniprobe list --batch` doesn't count incomplete tests towards `total_tests` in `result_summary`

**Comment by hellais** [comment]
I think that ideally we would handle the termination of tests in a more graceful way and in any case have some logic as part of probe-cli that does a cleanup of the database so that it doesn't leave broken/unreadable files lying around.

This is related to: https://github.com/ooni/probe-cli/issues/76
